name: player
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.6+6

environment:
  sdk: ">=3.0.0 <3.9.0"


dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12
  audio_video_progress_bar: ^2.0.0
  # google_mobile_ads: ^3.0.0
  bloc_concurrency: ^0.2.2
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.2
  just_audio: ^0.9.31
  on_audio_query: ^2.9.0
  path: ^1.8.2
  permission_handler: ^10.3.0
  rxdart: ^0.27.7
  sentry_flutter: ^7.13.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/clip.png"
  min_sdk_android: 21 


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
