name: player
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+6

environment:
  sdk: ">=3.0.0 <3.9.0"


dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.12
  audio_video_progress_bar: ^2.0.0
  # google_mobile_ads: ^3.0.0
  bloc_concurrency: ^0.2.2
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^5.2.5
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.2
  just_audio: ^0.9.31
  on_audio_query: ^2.9.0
  path: ^1.8.2
  permission_handler: ^10.3.0
  rxdart: ^0.27.7
  sentry_flutter: ^7.13.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/clip.png"
  min_sdk_android: 21 


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
